apiVersion: manifests.package-operator.run/v1alpha1
kind: PackageManifest
metadata:
  name: nginx
spec:
  scopes:
  - Namespaced
  phases:
  - name: deploy
  availabilityProbes:
  - probes:
    - condition:
        type: Available
        status: "True"
    - fieldsEqual:
        fieldA: .status.updatedReplicas
        fieldB: .status.replicas
    selector:
      kind:
        group: apps
        kind: Deployment
  config:
    openAPIV3Schema:
      type: object
      properties:
        addons:
          type: object
          description: "contains configuration passed by Addon Operator"
          properties:
            v1alpha1:
              type: object
              description: "contains configuration for addons.managed.openshift.io/v1alpha1"
              properties:
                deadManSnitchUrl:
                  type: string
                  description: "Dead Man's Snitch URL"
                pagerDutyKey:
                  type: string
                  description: "PagerDuty API key"
          required:
            - v1alpha1
test:
  template:
  - name: ado-injected-values
    context:
      package:
        metadata:
          name: my-cool-name
          namespace: test-ns
      config:
        addons:
          v1alpha1:
            deadManSnitchUrl: https://example.com/test-snitch-url
            pagerDutyKey: 1a2b3c4d5e6f