apiVersion: apps/v1
kind: Deployment
metadata:
  name: "my-cool-name"
  labels:
    app.kubernetes.io/name: nginx
    app.kubernetes.io/instance: "my-cool-name"
  annotations:
    package-operator.run/phase: deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/instance: "my-cool-name"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx
        app.kubernetes.io/instance: "my-cool-name"
    spec:
      containers:
        - name: nginx
          image: "1.23.4-alpine"
          ports:
            - containerPort: 80
          env:
            - name: MY_SNITCH_URL
              value: "https://example.com/test-snitch-url"
            - name: MY_PAGERDUTY_KEY
              value: "1a2b3c4d5e6f"